version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk
    environment:
#The idea was to have the version specified once and then referenced throughout the file however I didn't get this to work within the time
# which is why the version is hardcoded in other places
      - DEPLOY_VERSION: 3.0
    steps:
      - checkout
      - run: ./grailsw war target/petclinic-3.0.war
      - store_artifacts:
          path: target/petclinic-3.0.war
      - persist_to_workspace:
          root: target
          paths:
            - petclinic-3.0.war

  deploy:
    docker:
      - image: circleci/python:2.7
    environment:
      - DEPLOY_VERSION: 3.0
    steps:
      - checkout
      - attach_workspace:
          at: /tmp/target
      - run: sudo pip install ansible
      - run: ansible-playbook -i ansible/hosts ansible/deploy.yml -vv --syntax-check --extra-vars "path_to_war=/tmp/target/petclinic-3.0.war deploy_version=$DEPLOY_VERSION"
      - run: ansible-playbook -i ansible/hosts ansible/deploy.yml -vv --private-key PLEASE_REPLACE_ME --extra-vars "path_to_war=/tmp/target/petclinic-3.0.war deploy_version=$DEPLOY_VERSION"

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - deploy:
          requires:
            - build