version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk
    environment:
      - DEPLOY_VERSION: 3.0
    steps:
      - checkout
      #- run: export DEPLOY_VERSION=`git rev-parse --short HEAD` && echo $DEPLOY_VERSION
      - run: ./grailsw war petclinic-$DEPLOY_VERSION.war
      - store_artifacts:
          path: grails-app/target/*.war
      - persist_to_workspace:
          root: grails-app/target
          paths:
            - petclinic-3.0.war

  deploy:
    docker:
      - image: circleci/python:2.7
    environment:
      - DEPLOY_VERSION: 3
    steps:
      - checkout
   #   - run: export DEPLOY_VERSION=`git rev-parse --short HEAD` && echo $DEPLOY_VERSION
      - attach_workspace:
          at: /tmp/target
      - run: sudo pip install ansible
      - run: ansible-playbook -i hosts deploy.yml -vv --syntax-check --extra-vars "path_to_war=petclinic-$DEPLOY_VERSION.war deploy_version=$DEPLOY_VERSION"
      - run: ansible-playbook -i hosts deploy.yml --private-key PLEASE_REPLACE_ME --extra-vars "path_to_war=petclinic-$DEPLOY_VERSION.war deploy_version=$DEPLOY_VERSION"

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - deploy:
          requires:
            - build