---
- hosts: all
  become: true

  vars:
    path_to_war: target/petclinic.war
    deploy_version: 4.0

  tasks:
    - name: Updating apt repo
      apt:
        update_cache: yes

    - name: Install java8
      apt:
        state: latest
        pkg: openjdk-8-jdk

    - name: Install tomcat7
      apt:
        state: latest
        pkg: tomcat7

    - name: Move war into tomcat webapps dir
      copy:
        src: "{{ path_to_war }}"
        dest: /var/lib/tomcat7/webapps/petclinic-{{deploy_version}}.war

    - name: Change permissions on tomcat directory to allow h2 db lock creation
      file:
        path: /var/lib/tomcat7
        state: directory
        mode: 0755
        group: tomcat7
        owner: tomcat7

    - name: Add tomcat server.xml with custom config to run app on port 80 at the root context
      template:
        src: server.xml
        dest: /etc/tomcat7/server.xml

    - name: Allow tomcat to bind on port 80
      lineinfile:
        regexp: '#AUTHBIND=no'
        line: 'AUTHBIND=yes'
        path: /etc/default/tomcat7
        state: present

    - name: Restart tomcat
      service: name=tomcat7 state=restarted
      become: true

